#!/usr/bin/env python

from TAP import tap

import argparse

parser = argparse.ArgumentParser()

parser.add_argument('-q', '--query',  type=str, required=True, help='SQL query.')
parser.add_argument('-o', '--output', type=str,                help='Output table file.')
parser.add_argument('-f', '--format', type=str,                help='Output file format (default IPAC).')

parser.add_argument('-d', '--debug',  action = 'store_true',   help='Turn on debugging.')

args = parser.parse_args()

kwargs = vars(args)

tap.Tap(**kwargs)
